aspnet/AspNetKatana

- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs
- tests/Microsoft.Owin.Security.Tests/Cookies/CookieMiddlewareTests.cs
#29 When auth tickets are stored in the session store then a placeholder is created and serialized to the client. However, that placeholder does not have the IsPersistent flag set, so our renew logic would incorrectly renew persistent cookies.  Solution: read the properties from the original ticket.
@JaapMosselman
> Correctly renew persistent cookies when using SessionStore.

- build/Sakefile.shade
- src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationHandler.cs
- src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationHandler.cs
- tests/Katana.Sandbox.WebServer/Startup.cs
- tests/Microsoft.Owin.Security.Tests/Google/GoogleOAuth2MiddlewareTests.cs
https://github.com/aspnet/AspNetKatana/issues/38#issuecomment-291015826
When backporting the changes for the Facebook handler I left an extra `&` in the query string for the appsecret_proof param, which ends up getting escaped as `%26`. If you select `Require App Secret` in the Facebook app portal then it rejects requests with this extra encoded character. Note SendAppSecretProof is enabled by default, but Facebook does not validate it by default.
/cc: @erikarenhill @YovavGad
> Remove extra ampersand from appsecret_proof.

- build/Common.targets
#59 katana uses some old static analysis tools that do not understand C#6. This has lead to CI failures in the past. This change prevents C#6 from compiling in VS.
> Set LangVersion to restrict C# features.

- src/Microsoft.Owin.Security.MicrosoftAccount/Provider/MicrosoftAccountAuthenticatedContext.cs
#446 This broke in 3.1 due to a subtle null vs empty issue for the new MSA provider.
> Fix MicrosoftAccount email claim mapping

- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs
- tests/Microsoft.Owin.Security.Tests/Cookies/CookieMiddlewareTests.cs
#58 @AntonStokoz
Rejected identities would still end up creating an AuthTicket without a principal. If a sliding refresh was attempted on the same request then it would NRE on the missing principal.
The same code in ASP.NET Core has already been refactored so this should not be an issue there.
> Prevent NullReferenceException when identities are rejected and renewed

- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs
Fixed small spelling mistake in logging when no session id is found during AuthenticateCoreAsync
Addresses #100
> CookieAuthenticationHandler spelling fix

- src/Microsoft.Owin.Host.HttpListener/DisconnectHandler.cs
#108 
Disposed tokens cause ObjectDisposedExceptions when you try to register with them. Cancelled tokens immediately invoke your callback. If you cancel and dispose a token then there's a race where you may get a callback or an ODE. Disposal is only required for tokens that won't be cancelled, as cancellation does all of the same cleanup.
We did this for ASP.NET Core, we should backport it. Compare: 
https://github.com/aspnet/AspNetKatana/blob/5d58dab237663b694515a3adbb36dd246a7d4ca2/src/Microsoft.Owin.Host.HttpListener/DisconnectHandler.cs#L114-L132
https://github.com/aspnet/HttpSysServer/blob/dev/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/DisconnectListener.cs#L82-L120
> Don't dispose cancelled cancellation tokens

- src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationOptions.cs
- tests/FunctionalTests/Facts/Security/Facebook/FacebookAuthentication.cs
- tests/FunctionalTests/Facts/Security/Twitter/TwitterAuthentication.cs
#113 This is a backport of https://github.com/aspnet/Security/commit/e737f3207e8ceb80f6bcf1286b4ea0fec9ea72ea#diff-4621d8e36c62a3665d8427d0db85baa9.
https://github.com/aspnet/Security/blob/bd8ecd02684d490ece96c484e1092386f3515dec/src/Microsoft.AspNetCore.Authentication.Facebook/FacebookOptions.cs#L29-L34
It fixes a regression after we reacted to the Facebook API changes in 3.1 where facebook started requiring a scope and field added to the auth process to get e-mail addresses.
Note the change of Fields to a HashSet is needed because Facebook fails requests with duplicate field values and users may already be adding this field in their app. Facebook does not require unique Scope values, so we'll leave that one alone here.
> Include facebook scopes and fields by default

- src/Microsoft.Owin/Infrastructure/PathStringHelper.cs
- src/Microsoft.Owin/Microsoft.Owin.csproj
- src/Microsoft.Owin/PathString.cs
- tests/Microsoft.Owin.Tests/PathStringTests.cs
- tests/Microsoft.Owin.Tests/UriTests.cs
#104 This is a backport of https://github.com/aspnet/HttpAbstractions/commit/150b4708f158c0cdcc2d49f2ec72f3e82c6c64e4 to address PathString's over-encoding behavior. This catches Katana's PathString up to the same behaviors as Core.
> Improved encoding in PathString.ToUriComponent

- src/Microsoft.Owin.StaticFiles/Infrastructure/RangeHelpers.cs
- tests/Microsoft.Owin.StaticFiles.Tests/RangeHeaderTests.cs
#158. Not sure why this was using ints. This was re-written in Core.
> Parse long ranges

- src/Microsoft.Owin.Host.HttpListener/DisconnectHandler.cs
- tests/Microsoft.Owin.Host.HttpListener.Tests/OwinHttpListenerTests.cs
#141 This is a backport of a fix from Core:
https://github.com/aspnet/HttpSysServer/blob/4c388e89ce453a189aa861a40297a576aed14cdd/src/Microsoft.AspNetCore.Server.HttpSys/NativeInterop/DisconnectListener.cs#L114-L121
On Win8+ if async operations complete sync, such as the client already being disconnected, then we need to handle the async completion inline.
Verified using the manual repro code from the issue.
@maxcherednik
> Handle early disconnects 

- src/Microsoft.Owin.FileSystems/PhysicalFileSystem.cs
- tests/Microsoft.Owin.FileSystems.Tests/PhysicalFileSystemTests.cs
requests like "http://<server>/entity/**(**DefaultRouterOutlet:type**)**" throw on a windows system a NotSupportedException when the PhysicalFileSystem.TryGetFileInfo or PhysicalFileSystem.TryGetDirectoryContents is called. This results in a 500 instead of a 404. 
Catching this exception will prevent this issue.
> add exception handler for NotSupportedException

- src/Microsoft.Owin.Security.Google/Constants.cs
- src/Microsoft.Owin.Security.Google/Provider/GoogleOAuth2AuthenticatedContext.cs
- tests/Microsoft.Owin.Security.Tests/Google/GoogleOAuth2MiddlewareTests.cs
#251 This is conceptually the same fix as https://github.com/aspnet/AspNetCore/pull/6338, but the code is organized a bit differently here.
> Update Google auth user info endpoint 

- src/Microsoft.Owin.Cors/Microsoft.Owin.Cors.nuspec
- src/Microsoft.Owin.Diagnostics/Microsoft.Owin.Diagnostics.nuspec
- src/Microsoft.Owin.FileSystems/Microsoft.Owin.FileSystems.nuspec
- src/Microsoft.Owin.Host.HttpListener/Microsoft.Owin.Host.HttpListener.nuspec
- src/Microsoft.Owin.Host.SystemWeb/Microsoft.Owin.Host.SystemWeb.nuspec
- src/Microsoft.Owin.Hosting/Microsoft.Owin.Hosting.nuspec
- src/Microsoft.Owin.Security.ActiveDirectory/Microsoft.Owin.Security.ActiveDirectory.nuspec
- src/Microsoft.Owin.Security.Cookies/Microsoft.Owin.Security.Cookies.nuspec
- src/Microsoft.Owin.Security.Facebook/Microsoft.Owin.Security.Facebook.nuspec
- src/Microsoft.Owin.Security.Google/Microsoft.Owin.Security.Google.nuspec
- src/Microsoft.Owin.Security.Jwt/Microsoft.Owin.Security.Jwt.nuspec
- src/Microsoft.Owin.Security.MicrosoftAccount/Microsoft.Owin.Security.MicrosoftAccount.nuspec
- src/Microsoft.Owin.Security.OAuth/Microsoft.Owin.Security.OAuth.nuspec
- src/Microsoft.Owin.Security.OpenIdConnect/Microsoft.Owin.Security.OpenIdConnect.nuspec
- src/Microsoft.Owin.Security.Twitter/Microsoft.Owin.Security.Twitter.nuspec
- src/Microsoft.Owin.Security.WsFederation/Microsoft.Owin.Security.WsFederation.nuspec
- src/Microsoft.Owin.Security/Microsoft.Owin.Security.nuspec
- src/Microsoft.Owin.SelfHost/Microsoft.Owin.SelfHost.nuspec
- src/Microsoft.Owin.StaticFiles/Microsoft.Owin.StaticFiles.nuspec
- src/Microsoft.Owin.Testing/Microsoft.Owin.Testing.nuspec
- src/Microsoft.Owin/Microsoft.Owin.nuspec
- src/OwinHost/OwinHost.nuspec
#233 copyright was the only rule failing for for the main packages. I'll follow up for the loc satellite packages.
> Add missing package copyright

- README.md
The previous url for contribution documentation have a 404 error
> update the url for guideline of contribution

- src/Owin.Loader/DefaultLoader.cs
Assembly attributes will be instantiated only if same assembly contains any OwinStartup attribute(s)
> Issue #278 DefaultLoader now prefilters attributes before instantiating

- src/Microsoft.Owin/CookieOptions.cs
- src/Microsoft.Owin/Microsoft.Owin.csproj
- src/Microsoft.Owin/ResponseCookieCollection.cs
- src/Microsoft.Owin/SameSiteMode.cs
I have added a way to set SameSite attribute value for Set-Cookie headers.
You can do so by setting `CookieOptions.SameSite` property to some non null value.
If `CookieOptions.SameSite` property is null then SameSite attribute will not be added at all.
I must point out that if you use `SameSiteMode.None` it will be set as SameSite=None.
You can read about that behavior [here](https://web.dev/samesite-cookies-explained/) and [here](https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis-03#section-4.1)
> SameSite attribute support for ResponseCookieCollection

- src/Microsoft.Owin.Host.SystemWeb/SystemWebChunkingCookieManager.cs
- src/Microsoft.Owin.Host.SystemWeb/SystemWebCookieManager.cs
- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationHandler.cs
- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationOptions.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs
- src/Microsoft.Owin.Security/Infrastructure/AuthenticationHandler.cs
- src/Microsoft.Owin/Infrastructure/ChunkingCookieManager.cs
- src/Microsoft.Owin/ResponseCookieCollection.cs
- tests/Katana.Sandbox.WebServer/Katana.Sandbox.WebServer.csproj
- tests/Katana.Sandbox.WebServer/SameSiteCookieManager.cs
- tests/Katana.Sandbox.WebServer/Startup.cs
@blowdart we took a community PR https://github.com/aspnet/AspNetKatana/pull/299 that provided the initial SameSite implementation. This PR expands on that to more components, sets None for OIDC, lights up the System.Web implementation, etc..
The updated SystemWebCookieManager won't fix OIDC until System.Web gets patched.
I know there is some duplication here, this is old, decoupled code that we want to limit changes to.
Note that since this API never existed before we were able to make it nullable rather than adding Unspecified (-1) to the enum.
Also fixes https://github.com/aspnet/AspNetKatana/issues/234
> Use SameSite everywhere

- src/Microsoft.Owin.StaticFiles/StreamCopyOperation.cs
#304 The small copy buffer was causing perf issues on high latency connections.
> Use larger buffer for static file copy

- src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs
#315 This was a regression in 4.1 when adding the code flow support. It needed to check if the optional value was in the dictionary before trying to retrieve it. It was doing that a few lines down so I moved it up.
> Fix KeyNotFoundException in OIDCHandler.AuthenticateCoreAsync

- Katana.sln
- src/Microsoft.Owin.Host.HttpListener/OwinHttpListener.cs
- tests/Katana.Sandbox.Selfhost/App.config
- tests/Katana.Sandbox.Selfhost/Katana.Sandbox.Selfhost.csproj
- tests/Katana.Sandbox.Selfhost/Program.cs
- tests/Katana.Sandbox.Selfhost/Properties/AssemblyInfo.cs
- tests/Katana.Sandbox.Selfhost/packages.config
#314 OwinHttpListener assumed HttpListenerException would only be thrown if the HttpListener had been disposed. However, a partner identified another scenario where it can throw. These specialized catch blocks were redundant anyways, they all did the same thing. I've removed them and let everything fall through to the generic block. This now more close matches the code in [Core](https://github.com/aspnet/AspNetCore/blob/ec8304ae85d5a94cf3cd5efc5f89b986bc4eafd2/src/Servers/HttpSys/src/MessagePump.cs#L169).
@scottlerch
> HttpListener exception handling

- src/Microsoft.Owin/Infrastructure/OwinHelpers.cs
- src/Microsoft.Owin/RequestCookieCollection.cs
- tests/Microsoft.Owin.Tests/FormsTests.cs
- tests/Microsoft.Owin.Tests/Microsoft.Owin.Tests.csproj
- tests/Microsoft.Owin.Tests/RequestCookieTests.cs
https://github.com/dotnet/aspnetcore/issues/23578 https://github.com/dotnet/aspnetcore/pull/24264
Decoding arbitrary input allows spoofing of special inputs like __Host- with encoded values like __%48ost-.
Fix: Only compare to known values. e.g. the key the developer passes in with the encoding we would have used.
This fix works seamlessly for the indexer but leaves the encoded value in enumerator.
Note Katana does not have quirks or AppContext switches. That should be OK because Katana is not bundled as part of a framework, it's an opt-in package upgrade.
This PR had to do a little more more work than the AspNetCore 2.1 version because Katana shared the same parser for cookies, forms, and query strings. The three are close, but there are a few differences people have complained about …
> Remove cookie name decoding

- src/Microsoft.Owin/Infrastructure/OwinHelpers.cs
- tests/Microsoft.Owin.Tests/QueryTests.cs
This is a follow-up to #386. The analyzers caught a bug on a code path that was missing test coverage. It was replacing the pluses with spaces but not storing the result.
https://github.com/aspnet/AspNetKatana/pull/368/files#diff-b33820b73d48a2915e7fcf71cdd84297R563-R567
> Fix plus decoding

- build/Katana.version.targets
- build/Sakefile.shade
- src/Microsoft.Owin.Cors/Microsoft.Owin.Cors.nuspec
- src/Microsoft.Owin.Diagnostics/Microsoft.Owin.Diagnostics.nuspec
- src/Microsoft.Owin.FileSystems/Microsoft.Owin.FileSystems.nuspec
- src/Microsoft.Owin.Host.HttpListener/Microsoft.Owin.Host.HttpListener.nuspec
- src/Microsoft.Owin.Host.SystemWeb/Microsoft.Owin.Host.SystemWeb.nuspec
- src/Microsoft.Owin.Hosting/Microsoft.Owin.Hosting.nuspec
- src/Microsoft.Owin.Security.ActiveDirectory/Microsoft.Owin.Security.ActiveDirectory.nuspec
- src/Microsoft.Owin.Security.Cookies/Microsoft.Owin.Security.Cookies.nuspec
- src/Microsoft.Owin.Security.Facebook/Microsoft.Owin.Security.Facebook.nuspec
- src/Microsoft.Owin.Security.Google/Microsoft.Owin.Security.Google.nuspec
- src/Microsoft.Owin.Security.Jwt/Microsoft.Owin.Security.Jwt.nuspec
- src/Microsoft.Owin.Security.MicrosoftAccount/Microsoft.Owin.Security.MicrosoftAccount.nuspec
- src/Microsoft.Owin.Security.OAuth/Microsoft.Owin.Security.OAuth.nuspec
- src/Microsoft.Owin.Security.OpenIdConnect/Microsoft.Owin.Security.OpenIdConnect.nuspec
- src/Microsoft.Owin.Security.Twitter/Microsoft.Owin.Security.Twitter.nuspec
- src/Microsoft.Owin.Security.WsFederation/Microsoft.Owin.Security.WsFederation.nuspec
- src/Microsoft.Owin.Security/Microsoft.Owin.Security.nuspec
- src/Microsoft.Owin.SelfHost/Microsoft.Owin.SelfHost.nuspec
- src/Microsoft.Owin.StaticFiles/Microsoft.Owin.StaticFiles.nuspec
- src/Microsoft.Owin.Testing/Microsoft.Owin.Testing.nuspec
- src/Microsoft.Owin/Microsoft.Owin.nuspec
- src/OwinHost/OwinHost.nuspec
Fixes #319
Switch from the obsolete licenseUrl to license type="expression".
> Use License Expression 

- src/Microsoft.Owin.Security.Facebook/Constants.cs
- src/Microsoft.Owin.Security.Google/Constants.cs
- src/Microsoft.Owin.Security.MicrosoftAccount/Constants.cs
- src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationHandler.cs
- src/Microsoft.Owin/Infrastructure/OwinHelpers.cs
- tests/Katana.Sandbox.WebServer/Startup.cs
- tests/Microsoft.Owin.Tests/FormsTests.cs
#327 - our regular update of oauth endpoints. No observable behavior changes.
When manually testing I realized that #368 broke form decoding in two paces when replacing `+` with ` `.
The first was fixed by https://github.com/aspnet/AspNetKatana/pull/379
I've included the fix for the second one in this PR because WsFed doesn't work without it. In short, plus decoding needs to be turned on for forms parsing, we only needed to turn it off for cookies.
> Update OAuth endpoints, fix form un-escaping

- src/Microsoft.Owin.Security.OpenIdConnect/Microsoft.Owin.Security.OpenIdConnect.csproj
- src/Microsoft.Owin.Security.OpenIdConnect/OAuthConstants.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs
- tests/Katana.Sandbox.WebServer/Startup.cs
- tests/Microsoft.Owin.Security.Tests/Microsoft.Owin.Security.Tests.csproj
- tests/Microsoft.Owin.Security.Tests/OpenIdConnect/OpenIdConnectMiddlewareTests.cs
- tests/Microsoft.Owin.Security.Tests/packages.config
This adds PKCE Support to the OpenIdConnectAuthenticationHandler from #334 
The implementation is a port from ASP.NET Core respecting some of the missing APIs:
https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L386
and
https://github.com/dotnet/aspnetcore/blob/8a81194f372fa6fe63ded2d932d379955854d080/src/Security/Authentication/OpenIdConnect/src/OpenIdConnectHandler.cs#L1134
I've added some unit test to cover the challenge redirects and tested the implementation using the sandbox and IdentityServer4.
It could be possible to upgrade the [IdentityModel.*](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/releases) packages as well. But I'm not aware if …
> Backport ASP.NET Core PKCE Support to OpenIdConnectAuthenticationHandler

- src/Microsoft.Owin.Security.Facebook/Constants.cs
- tests/Microsoft.Owin.Security.Tests/Facebook/FacebookMiddlewareTests.cs
- tests/Microsoft.Owin.Security.Tests/Google/GoogleOAuth2MiddlewareTests.cs
#327 This is our regular refresh of OAuth endpoints. Only Facebook has changed, but a few of the other tests were out of date.
> Update Facebook OAuth endpoints, tests

- src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationNotifications.cs
Fixes #405. Users have been confused by SecurityTokenValidated, thinking it indicated that all authentication is finished. In fact it only refers to one step of the validation, the token itself. Adding a clarifying comment.
This should be ported forward to AspNetCore as well.
> Warn that SecurityTokenValidated is not that last step 

- src/Microsoft.Owin/Infrastructure/ChunkingCookieManager.cs
- tests/Microsoft.Owin.Tests/CookieChunkingTests.cs
Backporting this fix from AspNetCore. Some of the cookie chunks may be missing so we don't need to allocate space for or create delete cookies for cookies that we didn't receive.
> Handle mismatched cookie chunk counts

- azure-pipelines.yml
- src/Microsoft.Owin.Host.SystemWeb/SystemWebChunkingCookieManager.cs
- src/Microsoft.Owin.Security.ActiveDirectory/WsFedCachingSecurityKeyProvider.cs
- src/Microsoft.Owin.Security.ActiveDirectory/WsFedMetadataRetriever.cs
- src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationHandler.cs
- src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.WsFederation/WsFederationAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security/CertificateSubjectPublicKeyInfoValidator.cs
- src/Microsoft.Owin.Testing/TestServer.cs
These were mostly false positives with the exception of SM02185, server certificate revocation checks, which enabling now would be a breaking change. Customers can enable this themselves. I cleared this with @blowdart.
> Supress CodeQL warnings

- src/Microsoft.Owin.Security.Twitter/Microsoft.Owin.Security.Twitter.csproj
Not exactly a recent typo, but since we'll likely have a new release for the cookies stuff, it's probably a good opportunity to also fix the description of the Twitter package 😃
> Fix the description of the Twitter provider to mention OAuth 1.0 instead of OAuth 2.0

- src/Microsoft.Owin.Host.SystemWeb/OwinAppContext.cs
- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Cookies/CookieAuthenticationOptions.cs
- src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Facebook/FacebookAuthenticationOptions.cs
- src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Google/GoogleOAuth2AuthenticationOptions.cs
- src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.MicrosoftAccount/MicrosoftAccountAuthenticationOptions.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.OpenIdConnect/OpenIdConnectAuthenticationOptions.cs
- src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationMiddleware.cs
- src/Microsoft.Owin.Security.Twitter/TwitterAuthenticationOptions.cs
- src/Microsoft.Owin/Extensions/AppBuilderCookieExtensions.cs
- tests/Microsoft.Owin.Tests/Builder/AppBuilderCookieTests.cs
Related: https://github.com/aspnet/AspNetKatana/pull/485.
/cc @Tratcher
>  Allow OWIN hosts and applications to register default ICookieManager instances

- eng/Version.Details.xml
- global.json
- align better w/ the chosen .NET SDK in this repo
- will also allow Maestro++ PRs to keep the .NET SDK up-to-date automatically
> Switch to a 6.0.x Arcade SDK
